# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=100)),
                ('icon_cls', models.CharField(blank=True, default=None, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.CharField(default=None, max_length=100, null=True)),
                ('require_text', models.CharField(default=None, max_length=200, null=True)),
                ('require_source', models.CharField(default=None, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.Menu')),
            ],
        ),
    ]
